package com.usertest.entity;
// Generated 26/11/2019 11:27:50 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserInfoId generated by hbm2java
 */
@Embeddable
public class UserInfoId implements java.io.Serializable {

	private String username;
	private String usrfirstname;

	public UserInfoId() {
	}

	public UserInfoId(String username, String usrfirstname) {
		this.username = username;
		this.usrfirstname = usrfirstname;
	}

	@Column(name = "username", nullable = false, length = 25)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "usrfirstname", nullable = false, length = 50)
	public String getUsrfirstname() {
		return this.usrfirstname;
	}

	public void setUsrfirstname(String usrfirstname) {
		this.usrfirstname = usrfirstname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserInfoId))
			return false;
		UserInfoId castOther = (UserInfoId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getUsrfirstname() == castOther.getUsrfirstname())
						|| (this.getUsrfirstname() != null && castOther.getUsrfirstname() != null
								&& this.getUsrfirstname().equals(castOther.getUsrfirstname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getUsrfirstname() == null ? 0 : this.getUsrfirstname().hashCode());
		return result;
	}

}
