package com.usertest.entity;
// Generated 26/11/2019 11:27:50 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info")
public class UserInfo implements java.io.Serializable {

	private UserInfoId id;
	private Usuarios usuarios;
	private String usrlastname;
	private Integer usrage;
	private String usraddress;

	public UserInfo() {
	}

	public UserInfo(UserInfoId id, Usuarios usuarios) {
		this.id = id;
		this.usuarios = usuarios;
	}

	public UserInfo(UserInfoId id, Usuarios usuarios, String usrlastname, Integer usrage, String usraddress) {
		this.id = id;
		this.usuarios = usuarios;
		this.usrlastname = usrlastname;
		this.usrage = usrage;
		this.usraddress = usraddress;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 25)),
			@AttributeOverride(name = "usrfirstname", column = @Column(name = "usrfirstname", nullable = false, length = 50)) })
	public UserInfoId getId() {
		return this.id;
	}

	public void setId(UserInfoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "username", nullable = false, insertable = false, updatable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "usrlastname", length = 50)
	public String getUsrlastname() {
		return this.usrlastname;
	}

	public void setUsrlastname(String usrlastname) {
		this.usrlastname = usrlastname;
	}

	@Column(name = "usrage")
	public Integer getUsrage() {
		return this.usrage;
	}

	public void setUsrage(Integer usrage) {
		this.usrage = usrage;
	}

	@Column(name = "usraddress", length = 100)
	public String getUsraddress() {
		return this.usraddress;
	}

	public void setUsraddress(String usraddress) {
		this.usraddress = usraddress;
	}

}
