package com.usertest.entity;
// Generated 26-nov-2019 14:29:29 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info")
public class UserInfo implements java.io.Serializable {

	private String username;
	private String usrFirstname;
	private String usrLastname;
	private Integer usrAge;
	private String usrAddress;

	public UserInfo() {
	}

	public UserInfo(String username) {
		this.username = username;
	}

	public UserInfo(String username, String usrFirstname, String usrLastname, Integer usrAge, String usrAddress) {
		this.username = username;
		this.usrFirstname = usrFirstname;
		this.usrLastname = usrLastname;
		this.usrAge = usrAge;
		this.usrAddress = usrAddress;
	}

	@Id

	@Column(name = "username", unique = true, nullable = false, length = 25)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "usr_firstname", length = 50)
	public String getUsrFirstname() {
		return this.usrFirstname;
	}

	public void setUsrFirstname(String usrFirstname) {
		this.usrFirstname = usrFirstname;
	}

	@Column(name = "usr_lastname", length = 50)
	public String getUsrLastname() {
		return this.usrLastname;
	}

	public void setUsrLastname(String usrLastname) {
		this.usrLastname = usrLastname;
	}

	@Column(name = "usr_age")
	public Integer getUsrAge() {
		return this.usrAge;
	}

	public void setUsrAge(Integer usrAge) {
		this.usrAge = usrAge;
	}

	@Column(name = "usr_address", length = 100)
	public String getUsrAddress() {
		return this.usrAddress;
	}

	public void setUsrAddress(String usrAddress) {
		this.usrAddress = usrAddress;
	}

}
